"""add liking aoutgenerate

Revision ID: a3fce01e079d
Revises: 16a9a06d8350
Create Date: 2023-08-29 18:07:51.356126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3fce01e079d'
down_revision: Union[str, None] = '16a9a06d8350'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tblLikes',
    sa.Column('UserId', sa.Integer(), nullable=False),
    sa.Column('PostId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['PostId'], ['tblPosts.Id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['UserId'], ['tblUsers.Id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('UserId', 'PostId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tblLikes')
    # ### end Alembic commands ###
